services:
  - type: web
    name: openclaw
    runtime: docker
    plan: free # important: free is usually too small for OpenClaw
    healthCheckPath: /health
    envVars:
      - key: SETUP_PASSWORD
        sync: false
      - key: OPENCLAW_STATE_DIR
        value: /tmp/.openclaw
      - key: OPENCLAW_WORKSPACE_DIR
        value: /tmp/workspace
      - key: OPENCLAW_GATEWAY_TOKEN
        generateValue: true
      - key: HOST
        value: "0.0.0.0"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=768"
